// 104 ingrédients — catégories dans l'ordre d'affichage (voir SPEC §5 / §12)
const CATALOG = [
  { categorie: "Fruits", nom: "Pommes", emoji: "🍎", unite: "kg", prix_moyen_eur: 2.5, base_par_portion: 0.15 },
  { categorie: "Fruits", nom: "Bananes", emoji: "🍌", unite: "kg", prix_moyen_eur: 1.8, base_par_portion: 0.12 },
  { categorie: "Fruits", nom: "Oranges", emoji: "🍊", unite: "kg", prix_moyen_eur: 2.2, base_par_portion: 0.15 },
  { categorie: "Fruits", nom: "Poires", emoji: "🍐", unite: "kg", prix_moyen_eur: 2.6, base_par_portion: 0.15 },
  { categorie: "Fruits", nom: "Fraises", emoji: "🍓", unite: "paquet", prix_moyen_eur: 3.5, base_par_portion: 0.25 },
  { categorie: "Fruits", nom: "Raisins", emoji: "🍇", unite: "kg", prix_moyen_eur: 3.9, base_par_portion: 0.1 },
  { categorie: "Fruits", nom: "Citron", emoji: "🍋", unite: "pièce(s)", prix_moyen_eur: 0.5, base_par_portion: 0.25 },
  { categorie: "Fruits", nom: "Kiwi", emoji: "🥝", unite: "pièce(s)", prix_moyen_eur: 0.6, base_par_portion: 1 },
  { categorie: "Fruits", nom: "Pêches", emoji: "🍑", unite: "kg", prix_moyen_eur: 3.2, base_par_portion: 0.15 },
  { categorie: "Fruits", nom: "Ananas", emoji: "🍍", unite: "pièce(s)", prix_moyen_eur: 3, base_par_portion: 0.15 },
  { categorie: "Fruits", nom: "Pastèque", emoji: "🍉", unite: "pièce(s)", prix_moyen_eur: 4.5, base_par_portion: 0.1 },
  { categorie: "Fruits", nom: "Melon", emoji: "🍈", unite: "pièce(s)", prix_moyen_eur: 2.8, base_par_portion: 0.2 },
  { categorie: "Fruits", nom: "Cerises", emoji: "🍒", unite: "kg", prix_moyen_eur: 6, base_par_portion: 0.1 },
  { categorie: "Fruits", nom: "Myrtilles", emoji: "🫐", unite: "paquet", prix_moyen_eur: 3, base_par_portion: 0.2 },
  { categorie: "Fruits", nom: "Mangue", emoji: "🥭", unite: "pièce(s)", prix_moyen_eur: 1.8, base_par_portion: 0.3 },
  { categorie: "Fruits", nom: "Avocat", emoji: "🥑", unite: "pièce(s)", prix_moyen_eur: 1.2, base_par_portion: 0.5 },
  { categorie: "Fruits", nom: "Compote", emoji: "🍎", unite: "paquet", prix_moyen_eur: 2.5, base_par_portion: 0.3 },
  { categorie: "Légumes", nom: "Tomates", emoji: "🍅", unite: "kg", prix_moyen_eur: 2.8, base_par_portion: 0.15 },
  { categorie: "Légumes", nom: "Carottes", emoji: "🥕", unite: "kg", prix_moyen_eur: 1.2, base_par_portion: 0.12 },
  { categorie: "Légumes", nom: "Pommes de terre", emoji: "🥔", unite: "kg", prix_moyen_eur: 1.6, base_par_portion: 0.25 },
  { categorie: "Légumes", nom: "Oignons", emoji: "🧅", unite: "kg", prix_moyen_eur: 1.5, base_par_portion: 0.05 },
  { categorie: "Légumes", nom: "Ail", emoji: "🧄", unite: "pièce(s)", prix_moyen_eur: 0.7, base_par_portion: 0.1 },
  { categorie: "Légumes", nom: "Brocoli", emoji: "🥦", unite: "pièce(s)", prix_moyen_eur: 1.8, base_par_portion: 0.3 },
  { categorie: "Légumes", nom: "Chou-fleur", emoji: "🥦", unite: "pièce(s)", prix_moyen_eur: 2.2, base_par_portion: 0.25 },
  { categorie: "Légumes", nom: "Salade", emoji: "🥬", unite: "pièce(s)", prix_moyen_eur: 1.2, base_par_portion: 0.2 },
  { categorie: "Légumes", nom: "Épinards", emoji: "🥬", unite: "paquet", prix_moyen_eur: 2, base_par_portion: 0.2 },
  { categorie: "Légumes", nom: "Concombre", emoji: "🥒", unite: "pièce(s)", prix_moyen_eur: 1, base_par_portion: 0.25 },
  { categorie: "Légumes", nom: "Courgette", emoji: "🥒", unite: "pièce(s)", prix_moyen_eur: 1.1, base_par_portion: 0.4 },
  { categorie: "Légumes", nom: "Poivron", emoji: "🫑", unite: "pièce(s)", prix_moyen_eur: 0.9, base_par_portion: 0.4 },
  { categorie: "Légumes", nom: "Aubergine", emoji: "🍆", unite: "pièce(s)", prix_moyen_eur: 1.3, base_par_portion: 0.4 },
  { categorie: "Légumes", nom: "Champignons", emoji: "🍄", unite: "paquet", prix_moyen_eur: 1.9, base_par_portion: 0.25 },
  { categorie: "Légumes", nom: "Maïs", emoji: "🌽", unite: "boîte", prix_moyen_eur: 1.2, base_par_portion: 0.25 },
  { categorie: "Légumes", nom: "Haricots verts", emoji: "🫛", unite: "kg", prix_moyen_eur: 3.5, base_par_portion: 0.15 },
  { categorie: "Légumes", nom: "Petits pois", emoji: "🫛", unite: "boîte", prix_moyen_eur: 1.4, base_par_portion: 0.25 },
  { categorie: "Légumes", nom: "Patate douce", emoji: "🍠", unite: "kg", prix_moyen_eur: 2.5, base_par_portion: 0.2 },
  { categorie: "Légumes", nom: "Poireaux", emoji: "🥬", unite: "kg", prix_moyen_eur: 2.4, base_par_portion: 0.15 },
  { categorie: "Viandes & Poissons", nom: "Poulet", emoji: "🍗", unite: "kg", prix_moyen_eur: 8.5, base_par_portion: 0.15 },
  { categorie: "Viandes & Poissons", nom: "Dinde", emoji: "🦃", unite: "kg", prix_moyen_eur: 9.5, base_par_portion: 0.15 },
  { categorie: "Viandes & Poissons", nom: "Haché de boeuf", emoji: "🥩", unite: "kg", prix_moyen_eur: 8, base_par_portion: 0.125 },
  { categorie: "Viandes & Poissons", nom: "Steak", emoji: "🥩", unite: "kg", prix_moyen_eur: 15, base_par_portion: 0.15 },
  { categorie: "Viandes & Poissons", nom: "Lardons", emoji: "🥓", unite: "paquet", prix_moyen_eur: 2.2, base_par_portion: 0.2 },
  { categorie: "Viandes & Poissons", nom: "Jambon", emoji: "🍖", unite: "paquet", prix_moyen_eur: 2.8, base_par_portion: 0.15 },
  { categorie: "Viandes & Poissons", nom: "Saucisses", emoji: "🌭", unite: "pièce(s)", prix_moyen_eur: 0.9, base_par_portion: 1.2 },
  { categorie: "Viandes & Poissons", nom: "Saumon", emoji: "🐟", unite: "kg", prix_moyen_eur: 22, base_par_portion: 0.125 },
  { categorie: "Viandes & Poissons", nom: "Cabillaud", emoji: "🐟", unite: "kg", prix_moyen_eur: 18, base_par_portion: 0.13 },
  { categorie: "Viandes & Poissons", nom: "Poisson pané", emoji: "🐟", unite: "paquet", prix_moyen_eur: 3.2, base_par_portion: 0.3 },
  { categorie: "Viandes & Poissons", nom: "Thon en boîte", emoji: "🐟", unite: "boîte", prix_moyen_eur: 2.3, base_par_portion: 0.4 },
  { categorie: "Viandes & Poissons", nom: "Crevettes", emoji: "🦐", unite: "paquet", prix_moyen_eur: 5.5, base_par_portion: 0.25 },
  { categorie: "Viandes & Poissons", nom: "Oeufs", emoji: "🥚", unite: "pièce(s)", prix_moyen_eur: 0.35, base_par_portion: 1.5 },
  { categorie: "Produits laitiers", nom: "Lait", emoji: "🥛", unite: "L", prix_moyen_eur: 1.15, base_par_portion: 0.2 },
  { categorie: "Produits laitiers", nom: "Beurre", emoji: "🧈", unite: "paquet", prix_moyen_eur: 3.2, base_par_portion: 0.05 },
  { categorie: "Produits laitiers", nom: "Fromage", emoji: "🧀", unite: "paquet", prix_moyen_eur: 3.5, base_par_portion: 0.15 },
  { categorie: "Produits laitiers", nom: "Fromage râpé", emoji: "🧀", unite: "paquet", prix_moyen_eur: 2.4, base_par_portion: 0.15 },
  { categorie: "Produits laitiers", nom: "Mozzarella", emoji: "🧀", unite: "pièce(s)", prix_moyen_eur: 1.1, base_par_portion: 0.5 },
  { categorie: "Produits laitiers", nom: "Parmesan", emoji: "🧀", unite: "paquet", prix_moyen_eur: 3.8, base_par_portion: 0.05 },
  { categorie: "Produits laitiers", nom: "Yaourt", emoji: "🥛", unite: "pièce(s)", prix_moyen_eur: 0.55, base_par_portion: 1 },
  { categorie: "Produits laitiers", nom: "Crème fraîche", emoji: "🥛", unite: "pièce(s)", prix_moyen_eur: 1.4, base_par_portion: 0.2 },
  { categorie: "Épicerie", nom: "Pâtes", emoji: "🍝", unite: "g", prix_moyen_eur: 0.0026, base_par_portion: 100 },
  { categorie: "Épicerie", nom: "Riz", emoji: "🍚", unite: "g", prix_moyen_eur: 0.0022, base_par_portion: 80 },
  { categorie: "Épicerie", nom: "Semoule", emoji: "🌾", unite: "g", prix_moyen_eur: 0.002, base_par_portion: 80 },
  { categorie: "Épicerie", nom: "Lentilles", emoji: "🫘", unite: "g", prix_moyen_eur: 0.003, base_par_portion: 70 },
  { categorie: "Épicerie", nom: "Pois chiches", emoji: "🫘", unite: "boîte", prix_moyen_eur: 1.1, base_par_portion: 0.3 },
  { categorie: "Épicerie", nom: "Farine", emoji: "🌾", unite: "kg", prix_moyen_eur: 1, base_par_portion: 0.05 },
  { categorie: "Épicerie", nom: "Sucre", emoji: "🍬", unite: "kg", prix_moyen_eur: 1.1, base_par_portion: 0.02 },
  { categorie: "Épicerie", nom: "Sel", emoji: "🧂", unite: "kg", prix_moyen_eur: 0.8, base_par_portion: 0.005 },
  { categorie: "Épicerie", nom: "Huile d'olive", emoji: "🫒", unite: "L", prix_moyen_eur: 7.5, base_par_portion: 0.02 },
  { categorie: "Épicerie", nom: "Sauce tomate", emoji: "🥫", unite: "boîte", prix_moyen_eur: 1.5, base_par_portion: 0.3 },
  { categorie: "Épicerie", nom: "Pesto", emoji: "🌿", unite: "pièce(s)", prix_moyen_eur: 2.3, base_par_portion: 0.15 },
  { categorie: "Épicerie", nom: "Ketchup", emoji: "🍅", unite: "pièce(s)", prix_moyen_eur: 2.2, base_par_portion: 0.03 },
  { categorie: "Épicerie", nom: "Mayonnaise", emoji: "🫙", unite: "pièce(s)", prix_moyen_eur: 2.5, base_par_portion: 0.03 },
  { categorie: "Épicerie", nom: "Soupe", emoji: "🍲", unite: "L", prix_moyen_eur: 2.2, base_par_portion: 0.3 },
  { categorie: "Épicerie", nom: "Céréales", emoji: "🥣", unite: "boîte", prix_moyen_eur: 3.2, base_par_portion: 0.1 },
  { categorie: "Épicerie", nom: "Confiture", emoji: "🍓", unite: "pièce(s)", prix_moyen_eur: 2.5, base_par_portion: 0.03 },
  { categorie: "Épicerie", nom: "Miel", emoji: "🍯", unite: "pièce(s)", prix_moyen_eur: 4.5, base_par_portion: 0.02 },
  { categorie: "Épicerie", nom: "Pâte à tartiner", emoji: "🍫", unite: "pièce(s)", prix_moyen_eur: 3.5, base_par_portion: 0.03 },
  { categorie: "Épicerie", nom: "Beurre de cacahuète", emoji: "🥜", unite: "pièce(s)", prix_moyen_eur: 2.8, base_par_portion: 0.03 },
  { categorie: "Épicerie", nom: "Café", emoji: "☕", unite: "paquet", prix_moyen_eur: 5.5, base_par_portion: 0.03 },
  { categorie: "Épicerie", nom: "Thé", emoji: "🍵", unite: "boîte", prix_moyen_eur: 2.5, base_par_portion: 0.02 },
  { categorie: "Boulangerie", nom: "Pain", emoji: "🍞", unite: "pièce(s)", prix_moyen_eur: 2.4, base_par_portion: 0.2 },
  { categorie: "Boulangerie", nom: "Pain de mie", emoji: "🍞", unite: "paquet", prix_moyen_eur: 1.6, base_par_portion: 0.15 },
  { categorie: "Boulangerie", nom: "Baguette", emoji: "🥖", unite: "pièce(s)", prix_moyen_eur: 1.1, base_par_portion: 0.3 },
  { categorie: "Boulangerie", nom: "Croissant", emoji: "🥐", unite: "pièce(s)", prix_moyen_eur: 0.9, base_par_portion: 1 },
  { categorie: "Boulangerie", nom: "Pain au chocolat", emoji: "🥐", unite: "pièce(s)", prix_moyen_eur: 1, base_par_portion: 1 },
  { categorie: "Boulangerie", nom: "Pistolets", emoji: "🥯", unite: "pièce(s)", prix_moyen_eur: 0.4, base_par_portion: 1.5 },
  { categorie: "Boulangerie", nom: "Wraps", emoji: "🌯", unite: "paquet", prix_moyen_eur: 1.8, base_par_portion: 0.3 },
  { categorie: "Snacks & Goûter", nom: "Biscuits", emoji: "🍪", unite: "paquet", prix_moyen_eur: 2, base_par_portion: 0.15 },
  { categorie: "Snacks & Goûter", nom: "Speculoos", emoji: "🍪", unite: "paquet", prix_moyen_eur: 2.2, base_par_portion: 0.1 },
  { categorie: "Snacks & Goûter", nom: "Chocolat", emoji: "🍫", unite: "pièce(s)", prix_moyen_eur: 2.2, base_par_portion: 0.15 },
  { categorie: "Snacks & Goûter", nom: "Gaufres", emoji: "🧇", unite: "paquet", prix_moyen_eur: 2.2, base_par_portion: 0.25 },
  { categorie: "Snacks & Goûter", nom: "Crêpes", emoji: "🥞", unite: "paquet", prix_moyen_eur: 2, base_par_portion: 0.3 },
  { categorie: "Snacks & Goûter", nom: "Bonbons", emoji: "🍬", unite: "paquet", prix_moyen_eur: 2, base_par_portion: 0.1 },
  { categorie: "Snacks & Goûter", nom: "Chips", emoji: "🥔", unite: "paquet", prix_moyen_eur: 1.8, base_par_portion: 0.2 },
  { categorie: "Snacks & Goûter", nom: "Glace", emoji: "🍨", unite: "boîte", prix_moyen_eur: 3.5, base_par_portion: 0.15 },
  { categorie: "Snacks & Goûter", nom: "Fruits secs", emoji: "🥜", unite: "paquet", prix_moyen_eur: 2.6, base_par_portion: 0.1 },
  { categorie: "Boissons", nom: "Eau", emoji: "💧", unite: "L", prix_moyen_eur: 0.7, base_par_portion: 0.5 },
  { categorie: "Boissons", nom: "Jus d'orange", emoji: "🧃", unite: "L", prix_moyen_eur: 2, base_par_portion: 0.2 },
  { categorie: "Boissons", nom: "Jus de pomme", emoji: "🧃", unite: "L", prix_moyen_eur: 1.8, base_par_portion: 0.2 },
  { categorie: "Boissons", nom: "Limonade", emoji: "🥤", unite: "L", prix_moyen_eur: 1.5, base_par_portion: 0.2 },
  { categorie: "Boissons", nom: "Sirop de grenadine", emoji: "🧃", unite: "pièce(s)", prix_moyen_eur: 2.8, base_par_portion: 0.02 },
  { categorie: "Boissons", nom: "Chocolat chaud", emoji: "☕", unite: "boîte", prix_moyen_eur: 3, base_par_portion: 0.05 },
  { categorie: "Surgelés", nom: "Frites", emoji: "🍟", unite: "paquet", prix_moyen_eur: 2.5, base_par_portion: 0.25 },
  { categorie: "Surgelés", nom: "Pizza", emoji: "🍕", unite: "pièce(s)", prix_moyen_eur: 3, base_par_portion: 0.4 },
  { categorie: "Surgelés", nom: "Légumes surgelés", emoji: "🥦", unite: "paquet", prix_moyen_eur: 2, base_par_portion: 0.2 },
  { categorie: "Surgelés", nom: "Épinards à la crème", emoji: "🥬", unite: "paquet", prix_moyen_eur: 2.3, base_par_portion: 0.25 },
];

export default CATALOG;
